import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "ali-001",
    title: "Pro Smart Watch v2.4 - Health & Fitness Tracker",
    description: "Premium fitness smartwatch featuring continuous heart rate monitoring, sleep analysis, blood oxygen sensing, and 12+ sport modes. Up to 14 days of battery life, AMOLED crystal-clear touch display, and IP68 waterproof design.",
    category: "Electronics",
    price: 39.99,
    originalPrice: 89.99,
    discountRate: 55,
    rating: 4.8,
    reviewsCount: 1240,
    imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567801.html",
    features: [
      "AMOLED Display 1.43 inch with Always-On Mode",
      "Heart Rate & SpO2 Tracking",
      "IP68 Waterproof (Up to 50m depth)",
      "14 Days Long-Lasting Battery Life",
      "Smart Notifications & Bluetooth Calls"
    ],
    freeShipping: true,
    deliveryDays: 10,
    salesCount: 8430,
    storeName: "Global Tech Pioneers Co."
  },
  {
    id: "ali-002",
    title: "AuraSound Active Noise Cancelling Wireless Headphones",
    description: "Experience professional-grade acoustic clarity. Combining advanced Hybrid ANC tech, 40mm titanium drivers, ultra-soft memory-foam ear cushions, and ambient pass-through mode.",
    category: "Electronics",
    price: 45.50,
    originalPrice: 129.99,
    discountRate: 65,
    rating: 4.7,
    reviewsCount: 890,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567802.html",
    features: [
      "Hybrid ANC (Reduces noise up to 38dB)",
      "Hi-Res Audio Certified with Deep Bass",
      "50 Hours Playtime (ANC off)",
      "Bluetooth 5.3 Low-Latency Connection",
      "Foldable Space-Saving Carry Design"
    ],
    freeShipping: true,
    deliveryDays: 12,
    salesCount: 3210,
    storeName: "AuraSound Official Outlet"
  },
  {
    id: "ali-003",
    title: "Cinemax Ultra Portable 1080p Smart Mini Projector",
    description: "Transform any wall into a 150-inch cinematic theater. Runs Android OS natively, allowing Netflix, Prime, and YouTube streaming. Auto-keystone correction and built-in HiFi speaker.",
    category: "Electronics",
    price: 89.00,
    originalPrice: 199.99,
    discountRate: 55,
    rating: 4.6,
    reviewsCount: 560,
    imageUrl: "https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567803.html",
    features: [
      "Native 1080P Decoding, 400 ANSI Lumens",
      "Android OS Built-in with App Store",
      "Auto Focus & Auto Keystone Alignment",
      "Dual-Band WiFi 6 & Bluetooth Audio Out",
      "Display Size adjustable from 30\" to 150\""
    ],
    freeShipping: false,
    deliveryDays: 7,
    salesCount: 1540,
    storeName: "CinemaHome Electronics"
  },
  {
    id: "ali-004",
    title: "RetroClick Mechanical Keyboard - Custom Hot-Swappable",
    description: "Compact 75% mechanical gaming keyboard. Features high-quality tactile brown switches, beautiful custom PBT retro dye-sub keycaps, and customizable RGB backlighting profiles.",
    category: "Computers & Office",
    price: 54.90,
    originalPrice: 99.00,
    discountRate: 44,
    rating: 4.9,
    reviewsCount: 420,
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567804.html",
    features: [
      "Hot-Swappable 3/5-Pin Switch Socket",
      "Triple Connectivity (2.4Ghz, Bluetooth, USB-C)",
      "Premium PBT Double-Shot Keycaps",
      "Ergonomic Visual Retro Slate Palette",
      "Dampening Foam Layers for Satisfying Acoustics"
    ],
    freeShipping: true,
    deliveryDays: 14,
    salesCount: 980,
    storeName: "RetroClick Mechanical Hub"
  },
  {
    id: "ali-005",
    title: "NovaDock 8-in-1 Dual USB-C Hub Adapter Station",
    description: "An essential hub for laptops and tablets. Features 4K HDMI out, Gigabit Ethernet, SD card slot, and multiple USB 3.0 super-speed ports. Pass-through PD fast charging up to 100W.",
    category: "Computers & Office",
    price: 19.99,
    originalPrice: 39.99,
    discountRate: 50,
    rating: 4.5,
    reviewsCount: 2310,
    imageUrl: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567805.html",
    features: [
      "4K @ 60Hz HDMI Ultra-HD Output",
      "100W Power Delivery Quick Charge Pass-Through",
      "Gigabit Ethernet RJ45 High-Speed Port",
      "Dual USB 3.0 + USB-C Data Transfer Ports",
      "Premium Aluminum Alloy Heat Dissipation Shell"
    ],
    freeShipping: true,
    deliveryDays: 8,
    salesCount: 11200,
    storeName: "NovaLink Office Gear"
  },
  {
    id: "ali-006",
    title: "AeroClean Max Handheld Cordless Vacuum Cleaner",
    description: "Supercharged 15000Pa portable vacuum cleaner. Compact ergonomic structure, reusable HEPA dual filtration, and USB fast-charge battery. Exceptional for car detailing and home touch-ups.",
    category: "Home & Kitchen",
    price: 29.50,
    originalPrice: 69.99,
    discountRate: 57,
    rating: 4.6,
    reviewsCount: 1350,
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567806.html",
    features: [
      "120W High Performance Brushless Motor",
      "15000Pa Strong Instant Cyclone Suction",
      "Reusable, Washable High-Density HEPA Filter",
      "Cordless Lightweight Body (Only 450g)",
      "Multi-Functional Nozzle Accessories Included"
    ],
    freeShipping: true,
    deliveryDays: 10,
    salesCount: 4620,
    storeName: "AeroClean Home Appliance"
  },
  {
    id: "ali-007",
    title: "Minimalist Smart RFID Blocking Cardholder Wallet",
    description: "Engineered from space-grade aviation aluminum. Fits up to 8 credit cards with quick card pop-up mechanism and dedicated RFID shielding against electronic theft.",
    category: "Sports & Outdoors",
    price: 12.90,
    originalPrice: 29.99,
    discountRate: 56,
    rating: 4.8,
    reviewsCount: 4120,
    imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567807.html",
    features: [
      "One-Click Push Button Quick Eject Drawer",
      "Advanced RFID/NFC Blocking Shielding Tech",
      "Ultra-Slim 8.5mm Profile Travel Friendly",
      "Holds 1-8 Cards & Cash Under Carbon-Fiber Clip",
      "Corrosion-Resistant Aviation Aluminum Build"
    ],
    freeShipping: true,
    deliveryDays: 15,
    salesCount: 18900,
    storeName: "Urban Armor Gear"
  },
  {
    id: "ali-008",
    title: "EspressGo - Portable Travel Espresso Machine",
    description: "Take professional espresso shots wherever you venture. Operates on rechargeable USB power or manual hand pump. High 18 Bar pressure extracts rich crema from ground espresso or standard pods.",
    category: "Home & Kitchen",
    price: 49.99,
    originalPrice: 99.99,
    discountRate: 50,
    rating: 4.7,
    reviewsCount: 310,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567808.html",
    features: [
      "18 Bar High-Pressure Extraction System",
      "Dual Support: Coffee Powder or Nespresso Pods",
      "Built-in Rechargeable 2000mAh Battery",
      "Heating Capability: Brew with Cold or Hot Water",
      "BPA-Free Tritan Shell and Metallic Infuser"
    ],
    freeShipping: false,
    deliveryDays: 12,
    salesCount: 840,
    storeName: "EspressGo Outdoor Coffee"
  },
  {
    id: "ali-009",
    title: "Nomad Shield 35L Water-Resistant Sports Backpack",
    description: "Designed for modern explorers. Multi-layered structural compartments, padded 16-inch laptop pocket, USB device charging gateway, and breathable orthopedic back support pads.",
    category: "Sports & Outdoors",
    price: 32.50,
    originalPrice: 75.00,
    discountRate: 56,
    rating: 4.8,
    reviewsCount: 950,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567809.html",
    features: [
      "Premium High-Density Water-Resistant Oxford Fabric",
      "Integrated External USB Smart Charging Gateway",
      "35 Liters Modular Storage with Secret Security Pocket",
      "180-Degree Flat Opening TSA Friendly Airport Design",
      "Comfort-Airflow Mesh Orthopedic Shoulder Straps"
    ],
    freeShipping: true,
    deliveryDays: 11,
    salesCount: 2650,
    storeName: "Nomad Gear Labs"
  },
  {
    id: "ali-010",
    title: "DuoGlow Professional 10\" Ring Light & Tripod",
    description: "The ultimate lighting equipment for creators, streamers, and makeup artists. Dual warm/cool lighting presets, adjustable extendable tripod stand, and rotatable smart smartphone holder.",
    category: "Beauty & Health",
    price: 22.00,
    originalPrice: 49.99,
    discountRate: 56,
    rating: 4.6,
    reviewsCount: 1820,
    imageUrl: "https://images.unsplash.com/photo-1590650154751-121db7c27f4e?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567810.html",
    features: [
      "120 Premium LED Diodes, Multi-Level Brightness",
      "3 Color Modes: Warm Yellow, Warm White, Daylight",
      "Sturdy 62-Inch Extendable Metal Tripod Stand",
      "Flexible Phone Mount with Bluetooth Remote Shutter",
      "USB Plug-and-Play Power Supply (Power Bank Compatible)"
    ],
    freeShipping: true,
    deliveryDays: 9,
    salesCount: 5210,
    storeName: "DuoGlow Studio Lighting"
  },
  {
    id: "ali-011",
    title: "PureFace Ultrasonic Facial Cleansing Massage Brush",
    description: "Revitalize your skincare routine. Uses advanced sonic pulsation technology, medical-grade antibacterial soft silicone, and deep thermal facial heating nodes.",
    category: "Beauty & Health",
    price: 15.99,
    originalPrice: 39.99,
    discountRate: 60,
    rating: 4.7,
    reviewsCount: 630,
    imageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567811.html",
    features: [
      "Sonic Vibrations up to 8000 RPM",
      "IPX7 100% Waterproof Body - Shower Safe",
      "8 Speed Settings for Custom Facial Sensitivity",
      "Antibacterial Ultra-Soft Hypoallergenic Silicone Head",
      "Rechargeable Battery with Elegant Magnetic Charging Dock"
    ],
    freeShipping: true,
    deliveryDays: 14,
    salesCount: 1980,
    storeName: "PureSkin Cosmetics Hub"
  },
  {
    id: "ali-012",
    title: "AutoMount 15W Qi Wireless Car Charger & Mount",
    description: "Intelligent infrared sensors open/close the mount clamps automatically. Wireless quick charging up to 15W. Fits securely on any dashboard air vent.",
    category: "Electronics",
    price: 14.50,
    originalPrice: 29.99,
    discountRate: 51,
    rating: 4.5,
    reviewsCount: 1680,
    imageUrl: "https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=600&q=80",
    aliexpressUrl: "https://www.aliexpress.com/item/1005001234567812.html",
    features: [
      "Smart Infrared Sensor Auto-Clamping & Auto-Release",
      "15W High Efficiency QI Fast Wireless Charging",
      "360-Degree Spherical Pivot for Multi-Angle Viewing",
      "Inbuilt Supercapacitor (Opens even when car engine is off)",
      "Thick Silicone Anti-Slip Guards to Prevent Scratching"
    ],
    freeShipping: true,
    deliveryDays: 10,
    salesCount: 7300,
    storeName: "AutoGear Innovation Store"
  }
];

export const CATEGORIES = [
  "All Products",
  "Electronics",
  "Computers & Office",
  "Home & Kitchen",
  "Sports & Outdoors",
  "Beauty & Health"
];
